# The libraries used by your code should be listed here
name: rap_template # your project name (no spaces!)
channels:
  - default
  - conda-forge
dependencies:
  - python=3.10.5
  - pip
  - pandas=1.4.4
  - pyodbc=4.0.35
  - sqlalchemy=1.4.46
  - toml=0.10.2
