#A template of the conda environment
#The template contains commonly used packages
#For details: https://github.com/NHSDigital/rap-community-of-practice/blob/main/python/virtual-environments.md
name: rap

channels:
  - defaults

dependencies:
  - flake8=3.9.0
  - openpyxl
  - pip==20.2.4
  - python=3.9
  - pyodbc
  - ipykernel
  - ipython
  - nbconvert==6.0.7
  - numpy==1.19.5
  - pandas