# The libraries used by your code should be listed here
name: rap_template # your project name (no spaces!)
channels:
  - default
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pandas=1.4.4
  - pathlib2=2.3.7
  - pyodbc=4.0.32
  - sqlalchemy=1.4.36
  - toml=0.10.2
